formating comunication_protocol
ilaha/Austin_AniML_Rescue pull request #19
Opened 2021-09-08 00:22 UTC by ruthodeo

please leave comments if needed for formatting and spelling

2021-09-08 00:40 UTC, ilaha requested changes
There are some conflicts that need to be fixed before the merge :slightly_smiling_face:

2021-09-08 00:57 UTC, ruthodeo commented
> There are some conflicts that need to be fixed before the merge 🙂

i dont understand what is not working well there , i had commit 3 times thinking it would push without conflicts

2021-09-08 01:33 UTC, ilaha approved these changes

2021-09-08 01:34 UTC, ilaha commented
Looks good to me @ruthodeo .

Once someone else also confirms, I'll merge the commit :)

2021-09-08 20:34 UTC, SG314159 commented on README.md
> +## To ensure that the group receive consistent messages, we create a communication protocol outlines, where we identify the person responsibilities inside the final Bootcamp project.
Line 29 - Insert space between Communication and Protocol
Line 31 - Suggest changing to:   To ensure consistent messaging, we created a communication protocol outlining the responsibilities for each person in the group project.

2021-09-08 20:34 UTC, SG314159 commented on README.md
>  ### Everyone in the Austin AniML Rescue project has a role to play in communication:
Line 32 - Consider changing to:  Communication Roles

2021-09-08 20:34 UTC, SG314159 commented on README.md
> +     - Ilaha Mammadzada(square) is the manager and responsible for the repository.
Line 33 - Consider inserting:  The roles will change during the final project so that each member has the opportunity to learn about each piece of the project and practice the related skills.

Lines 34 to 42 - Consider replacing with more general descriptions since it is likely that we will rotate roles during the project.
- Role 1: Repository management. This team member leads efforts to maintain the GitHub repository, including resolving merge conflicts, and help keep the main branch as the source of our most recent working code. This person also updates the Readme.md file on the main branch as changes are made to the GitHub repo.
- Role 2: Project management. This team member leads the efforts for knowing what deliverables are required for the UT Bootcamp at each stage and assuring that the work the team is doing leads to successful fulfillment of the deliverables. This includes comparing the work to the rubric requirements as posted for class and helping to decide which technologies are used at each step of the project. 
- Role 3: ML modeling. This team member works on the coding aspect of the ML model as well as data cleaning and exploratory data analysis.
- Role 4: Database & Dashboard management. This team member maintains and updates the database (Postgres) as needed and leads the efforts for creating and maintaining our final dashboard.
- Role 5: Presentation management. This team member writes the presentation files and helps other team members as needed.

2021-09-08 20:34 UTC, SG314159 commented on README.md
> -## Everybody is responsible to voice their concerns and issues, provide feedbacks and listen to the other effectively.
Line 43 - Consider changing to:  Providing feedback on Group Work
Line 44 - 46:
- After committing work to the appropriate branch, submit a pull request once you believe the work is ready to be merged to the main branch.
- Two additional team members need to review the work as soon as possible and leave comments.
- A third team member completes the final review and merges the changes. This should be the person serving as the Repository manager for that week of the project.
- If significant changes are required to the commit, it is advised to ask the original author to revise the work and submit a new commit. Then the process starts again.

2021-09-08 20:34 UTC, SG314159 commented on README.md
> +### We had establish our best communication vehicles should be:
Line 49 - Consider changing to: Communication Tools and Timing

2021-09-09 00:09 UTC, ruthodeo commented
I just push the comunication_protocol updated.

2021-09-09 00:28 UTC, merged